name: Crystal CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt update && apt install -y cmake gcc g++ libstdc++-10-dev
    - name: Install crystal deps
      run: shards install
    - name: Build appp
      run: |
        cmake  -DCMAKE_BUILD_TYPE=Release . && cmake --build . --config Release
        shards build --release
    - name: Run benchmarks
      run: ./bin/rapidfuzz_benchmarks
      
