name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt update && apt install -y cmake gcc
    - name: Install crystal deps
      run: shards install
    - name: Build appp
      run: shards build --release
    - name: Run benchmarks
      run: ./bin/rapidfuzz_benchmarks
      
